### ISSUE TITLE
better to just list "days" until event? 

### ISSUE THREAD

**Issue by hpk42** [webratte/Event-Countdown#1]
am using your nice app in a 30-people group and one feedback was: "oh, it's only 27 days until ..." and the person (just like me) had overread "2 months".  I think it's better and simpler to just list the remaining days, so it would be "87 days" instead of (0 years, 2 months, 27 days).  what do you think?

**Comment by webratte** [comment]
Just days would be easier to calculate indeed.
I personally don't like it.
A period 1 year and 3 months seems more logical and better imaginable then 455 days I think.
Isn't it?

**Comment by webratte** [comment]
Maybe I could use a 1pixel bolder and coloured border around the number to make it better visible?

I think something like:
If month and year = 0 make a bolder and in table colour border around the number of days.

If month > 0 and year = 0 make a bolder and in table colour border around the number of months and days.

If year > 0 make bolder and in table colour border around the number of years months and days.

What do you think?

**Comment by webratte** [comment]
What about this solution?
Maybe a other colour?


![Screenshot_20230930-131449.png](https://github.com/webratte/Event-Countdown/assets/6864851/a2b1843b-a09a-45ec-9b80-e8346ac08f0c)

**Comment by webratte** [comment]
Closed by https://github.com/webratte/Event-Countdown/commit/c2e41b12416b38dde8108bbca932caa1aac3a68d

I realized it as on the screenshot. I think this should work for your "problem".

**Comment by hpk42** [comment]
as to "1 year" -- i am not sure that's an interesting use case for a "max 6 events" app.  
I would only use it for something in the next 2-3 months at most. 
But your choices/needs may vary -- no worries -- it's your app. 
If i care enough it's easy enough for me to fork the app and offer
an alternative version :)

**Comment by webratte** [comment]
Maybe it's not nesseary. But it also doesn't hurt if the most time year it's on "0".

My first entry was the end of our Housing loan in 1 year 5 month and 28 days 😉

Better there is "year" with less usage than missing it if it's needed.

And I think for you it's easier to start developing a similar app than try to understand my spaghetti code 😁

Thank you for your feedback anyway.

**Comment by hpk42** [comment]
thanks for caring!
